# Generated by Django 4.2 on 2024-09-14 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
